resolver: lts-21.11

packages:
    - src  # Uses the package.yaml in folder src

extra-deps:
    - alex-3.2.7       # For lexical analysis
    - happy-1.20.0     # For syntax analysis
    - hlint-3.3.6      # For static analysis

flags: {}

extra-package-dbs: []