name: jaspea
version: 0.1.0.0
license: MIT
author: Josué Mongan
maintainer: josuesmjr.mongan@gmail.com
synopsis: A graphical modeling language for robotics
category: Development

description: |
    Jaspea is a domain-specific language (DSL) for modeling,
    simulating, and visualizing robotic systems using graphs.

library:
    source-dirs: src
    exposed-modules:
        []
    dependencies:
        - base >= 4.14 && < 5
        - text
        - mtl
        - parsec

executables:
    jaspea:
        main: app/Main.hs
        source-dirs: .
        ghc-options: []
        dependencies:
            - jaspea
            - text
            - mtl
            - parsec
        build-tools:
            - alex
            - happy

tests:
    jaspea-test:
        main: test/SimulatorTest.hs
        source-dirs: .
        ghc-options: []
        dependencies:
            - jaspea
            - HUnit
            - QuickCheck
        build-tools:
            - happy
