name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up GHC with Stack
      uses: haskell/actions/setup@v1
      with:
        enable-stack: true

    - name: Cache Stack dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.stack
        key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml.lock') }}
        restore-keys: |
          ${{ runner.os }}-stack-

    - name: Install dependencies
      run: stack build --only-dependencies

    - name: Build project
      run: stack build --fast

    - name: Run tests
      run: stack test

    - name: Static analysis with HLint
      run: stack exec hlint src test

  docs:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Generate documentation
      run: |
        stack haddock --no-haddock-deps
        cp -r $(stack path --local-doc-root)/jaspea-* ./docs

    - name: Upload documentation
      uses: actions/upload-artifact@v3
      with:
        name: jaspea-docs
        path: ./docs
